# Generated by Django 3.2.2 on 2022-05-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
                ('num_likes', models.IntegerField()),
                ('num_dislikes', models.IntegerField()),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
